language: php
dist: bionic

php:
    - 7.3

services:
    - mysql


cache:
  npm: true
    directories:
        - ~/.cache
        - ~/.composer/cache

install:
  - npm ci
  - cp .env.testing .env
  - composer install --no-interaction --prefer-dist --no-suggest
  - npm install
  - npm run dev

before_script:
    - mysql -e 'create database local;'

script:
    - php artisan key:generate
    - php artisan migrate
    - php artisan db:seed
    - vendor/bin/phpunit
    - $(npm bin)/cypress run --record

after_success:
    - bash <(curl -s https://codecov.io/bash)
